- name: install mysql-server
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql-server
    ansible.builtin.dnf:
      name: mysql-server
      state: installed

  - name: start and enable nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

    