- name: Install mysql server
  hosts: mysql
  become: yes
  hosts:
  - name: Install mysql
    ansible.builtin.dnf:
      name: mysql-server
      state: installed
  
  - name: start and enable mysql service
    ansible.builtin.service:
      name: mysql-server
      state: started
      enable: yes
    
  - name: connect to mysql server
    community.mysql.mysql_db:
      login_user: root
      login_password: ExpenseApp@1
      login_host: 172.31.82.52
      register: mysql
      ignore_errors: true
